// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKBK3Uf5r4OmDGlSp7QE_6_jjSz1LVlnk',
    appId: '1:654280737606:web:f8209317243a88e9cb9b47',
    messagingSenderId: '654280737606',
    projectId: 'foodapp-f25b6',
    authDomain: 'foodapp-f25b6.firebaseapp.com',
    storageBucket: 'foodapp-f25b6.firebasestorage.app',
    measurementId: 'G-9DT09FT74X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6hZqbtrO8e2vXZSvdqMHEhLpNEZ3TmzI',
    appId: '1:654280737606:android:1f68896b57eeaa8acb9b47',
    messagingSenderId: '654280737606',
    projectId: 'foodapp-f25b6',
    storageBucket: 'foodapp-f25b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_8FWQ0rjp11QyE9inkt5Y6aqXfNZGb3E',
    appId: '1:654280737606:ios:49d89ff2d24a4883cb9b47',
    messagingSenderId: '654280737606',
    projectId: 'foodapp-f25b6',
    storageBucket: 'foodapp-f25b6.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_8FWQ0rjp11QyE9inkt5Y6aqXfNZGb3E',
    appId: '1:654280737606:ios:49d89ff2d24a4883cb9b47',
    messagingSenderId: '654280737606',
    projectId: 'foodapp-f25b6',
    storageBucket: 'foodapp-f25b6.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKBK3Uf5r4OmDGlSp7QE_6_jjSz1LVlnk',
    appId: '1:654280737606:web:0bb3dd5bc12f5f19cb9b47',
    messagingSenderId: '654280737606',
    projectId: 'foodapp-f25b6',
    authDomain: 'foodapp-f25b6.firebaseapp.com',
    storageBucket: 'foodapp-f25b6.firebasestorage.app',
    measurementId: 'G-Q2FFN1CTGZ',
  );
}
